// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWH03UhU8qdvE-lGYlG_Cf3El_XZYSbCI',
    appId: '1:68818408606:web:895e183ce924ccf515178f',
    messagingSenderId: '68818408606',
    projectId: 'fruits-app-d6166',
    authDomain: 'fruits-app-d6166.firebaseapp.com',
    storageBucket: 'fruits-app-d6166.appspot.com',
    measurementId: 'G-JJ3HP6RP0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSkCjdIsjSRFAEObTZrbpED_Jj3dNSoKk',
    appId: '1:68818408606:android:93fd966a71d4dfd715178f',
    messagingSenderId: '68818408606',
    projectId: 'fruits-app-d6166',
    storageBucket: 'fruits-app-d6166.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjKQFsYa0HYKT5iEF3oPAGxNMHnzpKgDo',
    appId: '1:68818408606:ios:ef565681abe23e3315178f',
    messagingSenderId: '68818408606',
    projectId: 'fruits-app-d6166',
    storageBucket: 'fruits-app-d6166.appspot.com',
    iosBundleId: 'com.example.fruitsMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjKQFsYa0HYKT5iEF3oPAGxNMHnzpKgDo',
    appId: '1:68818408606:ios:0c1805a2f8488eaf15178f',
    messagingSenderId: '68818408606',
    projectId: 'fruits-app-d6166',
    storageBucket: 'fruits-app-d6166.appspot.com',
    iosBundleId: 'com.example.fruitsMarket.RunnerTests',
  );
}
